version: '3'
services:
  client_information:
    build: ./customer_frontend
    volumes:
      - ./customer_frontend:/usr/src/app
    ports:
      - "3000:3000"
    restart: always
    # environment:
    #   CONN_URL: ""